name: ci-pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: |
        go mod tidy && git diff --exit-code
        go build ./cmd/... ./pkg/...
    - name: Format
      run: |
        diff=$(gofmt -s -d .)
        if [[ -n "${diff}" ]]; then echo "${diff}"; exit 1; fi
    - name: Test
      run: |
        go test -race ./cmd/... ./pkg/...
    - name: Run integration tests
      run: |
        cd test/integration
        go mod tidy && git diff --exit-code
        go test ./...
  required:
    # The name of the ci jobs above change based on the golang version.
    # Use this as a stable required job that depends on the above jobs.
    # ref: https://github.com/kubernetes/test-infra/pull/27016
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - run: echo "Required jobs success!"
